# Generated by Django 5.0.7 on 2024-07-15 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 15, 10, 21, 14, 648452, tzinfo=datetime.timezone.utc)),
        ),
    ]
