# Generated by Django 5.0.7 on 2024-07-17 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_comment_active_comment_email_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 17, 23, 39, 31, 133918, tzinfo=datetime.timezone.utc)),
        ),
    ]
